#!/usr/bin/env bash
# Ragnarok mechanical hypothesis gate.
#
# Inspects on-disk research/ artifacts (never conversation history) and
# determines whether Phases 0-4 are COMPLETE and the hypothesis gate is OPEN.
#
# Usage:
#   scripts/gate_check.sh [research-dir]
#   scripts/gate_check.sh [research-dir] --write
#
# Exit codes:
#   0  gate OPEN  (Phases 0-4 COMPLETE) and no violation
#   1  gate LOCKED
#   3  GATE VIOLATION (hypothesis/exploit work while LOCKED)
set -u

RESEARCH="research"
WRITE=0
for arg in "$@"; do
  if [ "$arg" = "--write" ]; then
    WRITE=1
  else
    RESEARCH="$arg"
  fi
done

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/gate_check.inc.sh
. "$HERE/lib/gate_check.inc.sh"

check_phase0; P0_REASONS=("${REASONS[@]}")
check_phase1; P1_REASONS=("${REASONS[@]}")
check_phase2; P2_REASONS=("${REASONS[@]}")
check_phase3; P3_REASONS=("${REASONS[@]}")
check_phase4; P4_REASONS=("${REASONS[@]}")
detect_violation

PENDING_LEADS="$(count_pending_leads)"

phase_status() {
  local -n reasons_ref="$1"
  [ "${#reasons_ref[@]}" -eq 0 ] && echo "COMPLETE" || echo "INCOMPLETE"
}

P0_STATUS="$(phase_status P0_REASONS)"
P1_STATUS="$(phase_status P1_REASONS)"
P2_STATUS="$(phase_status P2_REASONS)"
P3_STATUS="$(phase_status P3_REASONS)"
P4_STATUS="$(phase_status P4_REASONS)"

FIRST_BLOCKER=""
[ "$P0_STATUS" = "INCOMPLETE" ] && FIRST_BLOCKER="0"
[ -z "$FIRST_BLOCKER" ] && [ "$P1_STATUS" = "INCOMPLETE" ] && FIRST_BLOCKER="1"
[ -z "$FIRST_BLOCKER" ] && [ "$P2_STATUS" = "INCOMPLETE" ] && FIRST_BLOCKER="2"
[ -z "$FIRST_BLOCKER" ] && [ "$P3_STATUS" = "INCOMPLETE" ] && FIRST_BLOCKER="3"
[ -z "$FIRST_BLOCKER" ] && [ "$P4_STATUS" = "INCOMPLETE" ] && FIRST_BLOCKER="4"

if [ -z "$FIRST_BLOCKER" ]; then
  GATE="OPEN"
else
  GATE="LOCKED"
fi

if [ "$GATE" = "OPEN" ]; then
  VIOLATIONS=()
fi

render_phase_line() {
  local num="$1" status="$2"
  local -n reasons_ref="$3"
  if [ -n "$FIRST_BLOCKER" ] && [ "$num" -gt "$FIRST_BLOCKER" ]; then
    echo "Phase $num: BLOCKED (upstream Phase $FIRST_BLOCKER incomplete)"
    return
  fi
  echo "Phase $num: $status"
  local r
  for r in "${reasons_ref[@]}"; do
    echo "  $r"
  done
}

build_report() {
  echo "PHASE GATE CHECK"
  echo "generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) (source of truth: research-state files, not conversation history)"
  echo
  render_phase_line 0 "$P0_STATUS" P0_REASONS
  render_phase_line 1 "$P1_STATUS" P1_REASONS
  render_phase_line 2 "$P2_STATUS" P2_REASONS
  render_phase_line 3 "$P3_STATUS" P3_REASONS
  render_phase_line 4 "$P4_STATUS" P4_REASONS
  echo
  echo "Hypothesis Generation Gate (Phase 5+): $GATE"
  if [ "${#VIOLATIONS[@]}" -gt 0 ]; then
    echo
    echo "GATE VIOLATIONS DETECTED:"
    local v
    for v in "${VIOLATIONS[@]}"; do
      echo "  - $v"
    done
  fi
  echo
  echo "Action:"
  if [ "$GATE" = "OPEN" ]; then
    echo "GATE OPEN. Hypothesis generation, exploit construction, fuzzing, and deep"
    echo "falsification of a specific lead are permitted."
  else
    echo "DO NOT ADVANCE to hypothesis generation, exploit construction, fuzzing, or"
    echo "deep falsification of a specific lead."
    echo "Return to Phase $FIRST_BLOCKER reconstruction."
  fi
  if [ "${#VIOLATIONS[@]}" -gt 0 ]; then
    echo "GATE VIOLATION: work occurred ahead of the gate. Revert/queue it and return"
    echo "to reconstruction before continuing."
  fi
  echo "Pending leads preserved: $PENDING_LEADS"
}

REPORT="$(build_report)"
printf '%s\n' "$REPORT"

if [ "$WRITE" -eq 1 ]; then
  {
    echo "<!-- AUTO-GENERATED by scripts/gate_check.sh — do not hand-edit. Re-run the script to refresh. -->"
    echo "# Phase State Manifest"
    echo
    printf '%s\n' "$REPORT"
  } > "$RESEARCH/phase-state.md"
fi

if [ "${#VIOLATIONS[@]}" -gt 0 ]; then
  exit 3
fi
[ "$GATE" = "OPEN" ] && exit 0 || exit 1
