#!/usr/bin/env bash
# Apex Sentinel gate — ragnarok v4 + APPLICATION skip + substance override.
#
# Usage:
#   scripts/gate_check.sh [research-dir] [--write]
#
# Exit codes:
#   0  SYNTHESIS OPEN (incl. override / APPLICATION skip) and no real violation
#   1  SYNTHESIS LOCKED (thin map really missing)
#   3  GATE VIOLATION only when the research dir has no substance
set -u

RESEARCH="research"
WRITE=0
for arg in "$@"; do
  if [ "$arg" = "--write" ]; then
    WRITE=1
  else
    RESEARCH="$arg"
  fi
done

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VENDOR="$HERE/vendor/ragnarok/gate_check.sh"
SCOPE="$RESEARCH/scope.md"

is_application_layer() {
  [ -f "$SCOPE" ] || return 1
  grep -qiE 'Research layer:[[:space:]]*APPLICATION' "$SCOPE" && return 0
  grep -qiE 'Adapter:[[:space:]]*(application|ts|typescript|policy|mcp|cli)' "$SCOPE" && return 0
  grep -qiE 'PRODUCT_TYPE:.*(policy|mcp|cli|agent|keeperhub|typescript)' "$SCOPE" && return 0
  return 1
}

substance_open() {
  local r="$1"
  [ -f "$r/NOW.md" ] || return 1
  local bytes=0 f
  for f in architecture.md asset-flows.md trust-boundaries.md deployment.md; do
    if [ -f "$r/$f" ]; then
      bytes=$((bytes + $(wc -c < "$r/$f")))
    fi
  done
  [ "$bytes" -ge 3000 ] || return 1
  if grep -qE '0x[0-9a-fA-F]{40}' "$r/architecture.md" "$r/deployment.md" 2>/dev/null; then
    :
  elif grep -qiE 'program.id|ProgramId|pubkey|[1-9A-HJ-NP-Za-km-z]{32,44}' "$r/architecture.md" 2>/dev/null; then
    :
  else
    # application-layer maps may have neither; size + NOW.md is enough
    grep -qiE 'compose|policy|simulate|execute|workflow' "$r/architecture.md" 2>/dev/null || return 1
  fi
  grep -qE '^H-[0-9]+|^## CX-|^L-[0-9]+' "$r/hypotheses.md" "$r/killed.md" "$r/leads.md" "$r/contradictions.md" 2>/dev/null && return 0
  grep -qiE 'Gate:[[:space:]]*OPEN|Phase:[[:space:]]*[5-9]|residual|SYNTHESIS OPEN|CAMPAIGN OPEN' "$r/NOW.md" && return 0
  return 1
}

if is_application_layer; then
  echo "PHASE GATE CHECK (Apex v1.2 — APPLICATION skip)"
  echo "generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  echo "Research layer: APPLICATION"
  echo "Imagination Gate: OPEN (EVM reconstruction gate skipped)"
  echo "Campaign Gate: n/a"
  echo
  echo "Action:"
  echo "Hunt compose → policy → simulate → execute. Do not run ragnarok P2–P5."
  echo "Policy clock, kill switch, receiver, and dry-run correctness are in-scope."
  if [ "$WRITE" -eq 1 ]; then
    {
      echo "<!-- AUTO-GENERATED by apex scripts/gate_check.sh — APPLICATION skip -->"
      echo "# Phase State Manifest"
      echo
      echo "APPLICATION skip. SYNTHESIS OPEN."
    } > "$RESEARCH/phase-state.md"
  fi
  exit 0
fi

if [ ! -x "$VENDOR" ]; then
  echo "apex gate_check: vendored ragnarok v4 gate missing at $VENDOR" >&2
  exit 1
fi

set +e
if [ "$WRITE" -eq 1 ]; then
  VENDOR_OUT="$(bash "$VENDOR" "$RESEARCH" --write 2>&1)"
else
  VENDOR_OUT="$(bash "$VENDOR" "$RESEARCH" 2>&1)"
fi
VENDOR_RC=$?
set -e
printf '%s\n' "$VENDOR_OUT"

if [ "$VENDOR_RC" -eq 0 ]; then
  exit 0
fi

if substance_open "$RESEARCH"; then
  echo
  echo "Apex substance override: TOOLING LOCKED, hunt OPEN."
  echo "Vendored ragnarok v4 reported LOCKED/VIOLATION (rc=$VENDOR_RC) but research/"
  echo "already holds a real map + NOW.md + ledger. Do NOT restart P0–P5."
  echo "Treat Imagination Gate as SYNTHESIS OPEN. Continue residual (P8) or the"
  echo "cheapest unfalsified CX. See references/field-lessons.md §1."
  if [ "$WRITE" -eq 1 ]; then
    printf '\n\n## Apex substance override\nSYNTHESIS OPEN (tooling mismatch). Do not restart.\n' >> "$RESEARCH/phase-state.md"
  fi
  exit 0
fi

exit "$VENDOR_RC"
